### PR TITLE
matching_mode honored in cachedbs

### LINKED ISSUE #1801: [BUG] Matching mode ignored on cachedb+mongodb?
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 16:01:39 Aug  2 2019 with gcc 6.3.0

**Bug description**
I have a new installation of opensips  2.4.6 on debian 9.
I set a mongodb server for storing location data.
In my opensips.cfg i didn't set matching_mode so I assume the default value is used (0), in this configuration, when a register is processed by opensips,  the mongodb query should only match locations with the exact same contact.
As a consequence I dont expect to see multiple entries in the same collection with the same contact, but this is what happens:

at my mongodb prompt:
```
> use opensipsDB
switched to db opensipsDB
> db.userlocation.find({ "_id" : "#myusername#" }).pretty()
{
	"_id" : #myusername#,
	"aorhash" : 1838626049,
	"contacts" : {
		"c2lwOjA1NDcxOTU1MjY2QDYyLjk0LjIxLjE3Mjo1MDYwOjNhMDZiYjIyN2UxNzZlYjc0NGFkOGU5MzU0NGI3YThkQDEyNy4wLjAuMQ==" : {
			"attr" : null,
			"sip_instance" : null,
			"methods" : null,
			"sock" : "udp:239.0.0.7:5060",
			"path" : null,
			"received" : "sip:#recvip#:5060",
			"cflags" : "",
			"last_mod" : NumberLong(1565622835),
			"ua" : "FPBX-2.8.1(1.8.20.0)",
			"flags" : 1,
			"cseq" : 537,
			"callid" : "3a06bb227e176eb744ad8e93544b7a8d@127.0.0.1",
			"q" : 500,
			"expires" : 1565622955,
			"contact" : "sip:#myusername#@#myrecvip#:5060"
		},
		"c2lwOjA1NDcxOTU1MjY2QDYyLjk0LjIxLjE3Mjo1MDYwOjUwODE1MDJkMmIyNjVhN2Y1YTFlYWE3NTU4ZTM1OTE0QDEyNy4wLjAuMQ==" : {
			"attr" : null,
			"sip_instance" : null,
			"methods" : null,
			"sock" : "udp:239.0.0.7:5060",
			"path" : null,
			"received" : "sip:#myrecvip#:5060",
			"cflags" : "",
			"last_mod" : NumberLong(1565622836),
			"ua" : "FPBX-2.8.1(1.8.20.0)",
			"flags" : 1,
			"cseq" : 537,
			"callid" : "5081502d2b265a7f5a1eaa7558e35914@127.0.0.1",
			"q" : 500,
			"expires" : 1565622956,
			"contact" : "sip:#myusername#@#myrecvip#:5060"
		},
	}
}
```

In this case we have 2 records with same contact and different callid, this is unexpected, all i want is a new record with callid 3a06bb227e176eb744ad8e93544b7a8d@127.0.0.1 that gets replaced with callid 5081502d2b265a7f5a1eaa7558e35914@127.0.0.1 after the second register is verified.

I took a look at the code, it seems to me that the problem could be in function cdb_add_ct_update under modules/usrlocation/urecord.c

This function should take into account the matching_mode parameter and produce a base64hash according to contact only and not the combination callid+contact, am I wrong?

This is a snippet of my opensips.cfg

loadmodule "usrloc.so"
modparam("usrloc", "use_domain", 0)
modparam("usrloc", "working_mode_preset", "full-sharing-cachedb-cluster")
modparam("usrloc", "location_cluster", 1)
modparam("usrloc", "cachedb_url", "mongodb://10.0.253.143:27017/opensipsDB.userlocation")
modparam("usrloc", "nat_bflag", "NAT")
modparam("usrloc", "skip_replicated_db_ops", 0)
loadmodule "registrar.so"
modparam("registrar", "default_q", 500)
modparam("registrar", "min_expires", 60)
modparam("registrar", "max_expires", 259200)
modparam("registrar", "default_expires", 1800)
modparam("registrar", "max_contacts", 3)
modparam("registrar", "retry_after", 300)
modparam("registrar", "sock_hdr_name", "Sock-Info")
modparam("registrar", "tcp_persistent_flag", "TCP_PERSISTENT")
modparam("registrar", "received_avp", "$avp(received_nh)")

**OS/environment information**
 - Operating System: Debian 9 Jessie
 - OpenSIPS installation: Opensips 2.4.6 downloaded from github at https://github.com/OpenSIPS/opensips/releases/tag/2.4.6

### PR DESCRIPTION
**Pull request by Ozzyboshi**
This fix works for me, i set modparam("usrloc", "matching_mode", 0) on my opensips.cfg and now I have one entry only for each contact as expected.
Actually setting matching_mode at zero is useless because it's the default behaviour, however I like to state it explicitly in the configuration file.
Please consider merging it and if yes, porting this fix in the 2.4 branch since for now I am only using Opensips 2.4 series.

This fix should close #1801.

### CODE REVIEW

File: modules/usrloc/urecord.c [hunk 1]
```diff
@@ -501,24 +501,44 @@ int cdb_add_ct_update(cdb_dict_t *updates, const ucontact_t *ct, char remove)
...
-	}
-
-	memcpy(ctkey_pkg_buf.s, ct->c.s, ct->c.len);
-	ctkey_pkg_buf.s[ct->c.len] = ':';
-	memcpy(ctkey_pkg_buf.s + ct->c.len + 1, ct->callid.s,
-	       ct->callid.len);
-
+	
+	switch (matching_mode) {
+                case CONTACT_ONLY:
```
Comment (liviuchircu) [inline modules/usrloc/urecord.c]:
```suggestion:+33
	case CONTACT_ONLY:
		len = ct->c.len;
		base64len = calc_base64_encode_len(len);
		if (pkg_str_extend(&ctkey_pkg_buf, len) < 0) {
			LM_ERR("oom\n");
			return -1;
		}

		if (pkg_str_extend(&ctkeyb64_pkg_buf, base64len) < 0) {
			LM_ERR("oom\n");
			return -1;
		}

		memcpy(ctkey_pkg_buf.s, ct->c.s, ct->c.len);
		break;
	case CONTACT_CALLID:
		len = ct->c.len + 1 + ct->callid.len;
		base64len = calc_base64_encode_len(len);
		if (pkg_str_extend(&ctkey_pkg_buf, len) < 0) {
			LM_ERR("oom\n");
			return -1;
		}

		if (pkg_str_extend(&ctkeyb64_pkg_buf, base64len) < 0) {
			LM_ERR("oom\n");
			return -1;
		}
		memcpy(ctkey_pkg_buf.s, ct->c.s, ct->c.len);
		ctkey_pkg_buf.s[ct->c.len] = ':';
		memcpy(ctkey_pkg_buf.s + ct->c.len + 1, ct->callid.s,
		               ct->callid.len);
		break;
	default:
		LM_CRIT("unknown matching_mode %d\n", matching_mode);
		return -1;
```

**Comment by Ozzyboshi** [comment]
I replaced spaces with tabs and put cases at the same level of the switch keyword.
Please take another look at the code, now it should be fine with your coding standards, if not please let me know.
If anyone will complain about the number of records of their location, they have just to set matching_mode = 1 as stated in Opensips docs and readme.
In my opinion the code should reflect what the documentation says, it's strange that anyone didnt notice before me.

**Comment by liviuchircu** [comment]
Storing all usrloc data in NoSQL is available starting with May 2018, so within more or less a year, it makes sense for the feature to be only picked up by early adopters, while the majority of users have stuck to what has worked well up until then: "if it ain't broke, don't fix it!"
